config/routes.rb
Rails.application.routes.draw do
  resources :stores
  resources :menus
  resources :posts
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :store
  has_many :posts
  has_many :users, through: :posts

  accepts_nested_attributes_for :store
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :menu

  accepts_nested_attributes_for :user
  accepts_nested_attributes_for :menu
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :menus
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :menus, through: :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @q = Menu.ransack(params[:q])
    @menus = @q.result.page(params[:page]).per_page(5)
    @title = I18n.t("menus")
  end

  def show
    @menu = Menu.find(params[:id])
    @posts = @menu.posts.includes(:user, menu: [:store])
    @users = @menu.users
    @title = "#{I18n.t("menu")} : #{@menu.name}"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :validate_user, only: [:update, :destroy]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result.includes(:user, menu: :store).page(params[:page]).per_page(10)
    @title = I18n.t("posts")
  end

  def new
    @post = Post.new
    @post.user = User.new # TODO 로그인 처리
    @post.menu = Menu.new
    @post.menu.store = Store.new
    @title = I18n.t("new_post")
  end

  def create
    @post = Post.new(post_params)
    @user = User.find_or_initialize_by(name: user_params[:name]) # TODO 로그인 처리
    @store = Store.find_or_initialize_by(name: store_params[:name])
    @menu = Menu.find_or_initialize_by(name: post_params[:name])
    @user.attributes = user_params
    @store.attributes = store_params
    @menu.attributes = menu_params
    @menu.store = @store
    @post.user = @user
    @post.menu = @menu
    @post.save!
    redirect_to post_path(@post)
  rescue ActiveRecord::RecordInvalid => e
    flash[:alert] = e.message
    render "new"
  end

  def show
    @title = I18n.t("post")
  end

  def edit
    @title = I18n.t("edit_post")
  end

  def update
    @post.attributes = post_params
    @post.save!
    redirect_to post_path(@post)
  rescue ActiveRecord::RecordInvalid => e
    flash[:alert] = e.message
    render "edit"
  end

  def destroy
    @post.destroy!
    redirect_to posts_path, flash: { notice: I18n.t("destroy_completed") }
  rescue ActiveRecord::RecordNotDestroyed => e
    redirect_back fallback_location: post_path(@post), flash: { alert: e.message }
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:context, :may_retry, menu_attributes: [:id, :price])
  end

  def user_params
    params.require(:post).require(:user_attributes).permit(:id, :name)
  end

  def menu_params
    params.require(:post).require(:menu_attributes).permit(:id, :name, :price)
  end

  def store_params
    params.require(:post).require(:menu_attributes).require(:store_attributes).permit(:id, :name)
  end

  def validate_user
    # TODO 로그인 처리 후 삭제
    unless @post.user.name == user_params[:name]
      redirect_back fallback_location: :root_path, flash: { alert: I18n.t("invalid_user", user_name: user_params[:name]) }
    end
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
    @q = Store.ransack(params[:q])
    @stores = @q.result.page(params[:page]).per_page(10)
    @title = I18n.t("stores")
  end

  def show
    @store = Store.find(params[:id])
    @menus = @store.menus
    @posts = Post.joins(:menu).where(menus: {store_id: @store.id}).includes(:user, menu: [:store])
    @users = @posts.map(&:user).uniq
    @title = "#{I18n.t("store")} : #{@store.name}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @q = User.ransack(params[:q])
    @users = @q.result.page(params[:page]).per_page(10)
    @title = I18n.t("users")
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.includes(:user, menu: [:store])
    @title = "#{I18n.t("user")} : #{@user.name}"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @context = "Welcome Swatchon Lunch Blog!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Jquery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="row">
      <div class="col-12 col-lg-2 px-4 py-5 bg-secondary">
        <div>
          <%= link_to I18n.t("posts"), posts_path %>
        </div>
        <div>
          <%= link_to I18n.t("users"), users_path %>
        </div>
        <div>
          <%= link_to I18n.t("menus"), menus_path %>
        </div>
        <div>
          <%= link_to I18n.t("stores"), stores_path %>
        </div>
      </div>
      <div class="col-12 col-lg-10 p-4">
        <% flash.each do |key, message| %>
          <div class="border rounded mb-4 border-danger text-danger">
            <%= key %>: <%= message %>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/menus/_share_index.html.erb
<div class="card p-4 mt-5">
  <div class="table-responsive">
    <table class="table">
      <thead>
      <tr>
        <th><%= I18n.t("menu_name") %></th>
        <th><%= I18n.t("menu_price") %></th>
        <th><%= I18n.t("created_at") %></th>
        <th><%= I18n.t("updated_at") %></th>
      </tr>
      </thead>
      <tbody>
      <% menus.each do |menu| %>
        <tr>
          <td><%= link_to menu.name, menu_path(menu) %></td>
          <td><%= number_with_delimiter menu.price %></td>
          <td><%= menu.created_at.to_s %></td>
          <td><%= menu.updated_at.to_s %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/menus/index.html.erb
<%= search_form_for @q do |f| %>
  <div class="card p-4">
    <div class="row">
      <div class="col-12 col-md-6 col-lg-3 form-set">
        <%= f.label :name_cont, I18n.t("name") %>
        <%= f.text_field :name_cont, class: "form-control" %>
      </div>
    </div>

    <div class="row justify-content-end">
      <div class="col-auto">
        <%= f.submit t("search"), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

<div class="card p-4 mt-5">
  <h3><%= I18n.t("search_results") %> (<%= @q.result.count %>)</h3>

  <div class="table-responsive">
    <table class="table">
      <thead>
      <tr>
        <th><%= I18n.t("name") %></th>
        <th><%= I18n.t("created_at") %></th>
        <th><%= I18n.t("updated_at") %></th>
      </tr>
      </thead>
      <tbody>
      <% @menus.each do |menu| %>
        <tr>
          <td><%= link_to menu.name, menu_path(menu) %></td>
          <td><%= menu.created_at.to_s %></td>
          <td><%= menu.updated_at.to_s %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <%= will_paginate @menus %>
  </div>
</div>

app/views/menus/show.html.erb
<div class="row">
  <div class="col-3">
    <%= I18n.t("menu_name") %>
  </div>
  <div class="col-9">
    <%= @menu.name %>
  </div>

  <div class="col-3">
    <%= I18n.t("menu_price") %>
  </div>
  <div class="col-9">
    <%= number_with_delimiter @menu.price %>
  </div>

  <div class="col-3">
    <%= I18n.t("store_name") %>
  </div>
  <div class="col-9">
    <%= link_to @menu.store.name, store_path(@menu.store) %>
  </div>

  <div class="col-3">
    <%= I18n.t("created_at") %>
  </div>
  <div class="col-9">
    <%= @menu.created_at %>
  </div>

  <div class="col-3">
    <%= I18n.t("updated_at") %>
  </div>
  <div class="col-9">
    <%= @menu.updated_at %>
  </div>
</div>


<%= render "/posts/share_index", posts: @posts %>
<%= render "/users/share_index", users: @users %>

app/views/posts/_share_index.html.erb
<div class="card p-4 mt-5">
  <div class="table-responsive">
    <table class="table">
      <thead>
      <tr>
        <th>ID</th>
        <th><%= I18n.t("user_name") %></th>
        <th><%= I18n.t("menu_name") %></th>
        <th><%= I18n.t("store_name") %></th>
        <th><%= I18n.t("post_may_retry") %></th>
        <th><%= I18n.t("created_at") %></th>
        <th><%= I18n.t("updated_at") %></th>
      </tr>
      </thead>
      <tbody>
      <% posts.each do |post| %>
        <tr>
          <td><%= link_to post.id, post_path(post) %></td>
          <td><%= link_to post.user.name, user_path(post.user) %></td>
          <td><%= link_to post.menu.name, menu_path(post.menu) %></td>
          <td><%= link_to post.menu.store.name, store_path(post.menu.store) %></td>
          <td><%= I18n.t("post_may_retry_#{post.may_retry.to_s}") %></td>
          <td><%= post.created_at.to_s %></td>
          <td><%= post.updated_at.to_s %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/posts/edit.html.erb
<%= form_for @post, method: :put do |f| %>
  <%= f.fields_for :user do |ff| %>
    <%= ff.label :name, I18n.t("user_name") %>
    <%= ff.text_field :name, value: nil, required: true, class: "form-control" %>
  <% end %>

  <%= f.fields_for :menu do |ff| %>
    <%= ff.label :name, I18n.t("menu_name") %>
    <%= ff.text_field :name, disabled: true, class: "form-control" %>

    <%= ff.label :price, I18n.t("menu_price") %>
    <%= ff.number_field :price, required: true, class: "form-control" %>

    <%= ff.fields_for :store do |fff| %>
      <%= fff.label :name, I18n.t("store_name") %>
      <%= fff.text_field :name, disabled: true, class: "form-control" %>
    <% end %>
  <% end %>

  <%= f.label :context, I18n.t("post_context") %>
  <%= f.text_area :context, required: true, rows: 10, class: "form-control" %>

  <%= f.label :may_retry, I18n.t("post_may_retry") %>
  <%= f.check_box :may_retry %>

  <div>
    <%= f.submit I18n.t("update"), class: "btn btn-primary my-3" %>
  </div>
<% end %>

app/views/posts/index.html.erb
<%= search_form_for @q do |f| %>
  <div class="card p-4">
    <div class="row">
      <div class="col-12 col-md-6 col-lg-3 form-set">
        <%= f.label :user_name_cont, I18n.t("user_name") %>
        <%= f.text_field :user_name_cont, class: "form-control" %>
      </div>
      <div class="col-12 col-md-6 col-lg-3 form-set">
        <%= f.label :menu_name_cont, I18n.t("menu_name") %>
        <%= f.text_field :menu_name_cont, class: "form-control" %>
      </div>
      <div class="col-12 col-md-6 col-lg-3 form-set">
        <%= f.label :menu_store_name_cont, I18n.t("store_name") %>
        <%= f.text_field :menu_store_name_cont, class: "form-control" %>
      </div>
    </div>

    <div class="row justify-content-end">
      <div class="col-auto">
        <%= f.submit t("search"), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

<div class="card p-4 mt-5">
  <h3><%= I18n.t("search_results") %> (<%= @q.result.count %>)</h3>

  <div class="row justify-content-end">
    <div class="col-auto">
      <%= link_to I18n.t("new_post"), new_post_path, class: "btn btn-primary" %>
    </div>
  </div>

  <div class="table-responsive">
    <table class="table">
      <thead>
      <tr>
        <th>ID</th>
        <th><%= I18n.t("user_name") %></th>
        <th><%= I18n.t("menu_name") %></th>
        <th><%= I18n.t("store_name") %></th>
        <th><%= I18n.t("post_may_retry") %></th>
        <th><%= I18n.t("created_at") %></th>
        <th><%= I18n.t("updated_at") %></th>
      </tr>
      </thead>
      <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= link_to post.id, post_path(post) %></td>
          <td><%= link_to post.user.name, user_path(post.user) %></td>
          <td><%= link_to post.menu.name, menu_path(post.menu) %></td>
          <td><%= link_to post.menu.store.name, store_path(post.menu.store) %></td>
          <td><%= I18n.t("post_may_retry_#{post.may_retry}") %></td>
          <td><%= post.created_at.to_s %></td>
          <td><%= post.updated_at.to_s %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <%= will_paginate @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<%= form_for(@post) do |f| %>
  <%= f.fields_for :user do |ff| %>
    <%= ff.label :name, I18n.t("user_name") %>
    <%= ff.text_field :name, required: true, class: "form-control" %>
  <% end %>

  <%= f.fields_for :menu do |ff| %>
    <%= ff.fields_for :store do |fff| %>
      <%= fff.label :name, I18n.t("store_name") %>
      <%= fff.text_field :name, required: true, class: "form-control" %>
    <% end %>

    <%= ff.label :name, I18n.t("menu_name") %>
    <%= ff.text_field :name, required: true, class: "form-control" %>

    <%= ff.label :price, I18n.t("menu_price") %>
    <%= ff.number_field :price, required: true, class: "form-control" %>
  <% end %>

  <%= f.label :context, I18n.t("post_context") %>
  <%= f.text_area :context, required: true, rows: 10, class: "form-control" %>

  <%= f.label :may_retry, I18n.t("post_may_retry") %>
  <%= f.check_box :may_retry %>

  <div>
    <%= f.submit I18n.t("create"), class: "btn btn-primary my-3" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-3">
    <%= I18n.t("user_name") %>
  </div>
  <div class="col-9">
    <%= link_to @post.user.name, user_path(@post.user) %>
  </div>

  <div class="col-3">
    <%= I18n.t("menu_name") %>
  </div>
  <div class="col-9">
    <%= link_to @post.menu.name, menu_path(@post.menu) %>
  </div>
  <div class="col-3">
    <%= I18n.t("menu_price") %>
  </div>
  <div class="col-9">
    <%= number_with_delimiter @post.menu.price %>
  </div>

  <div class="col-3">
    <%= I18n.t("store_name") %>
  </div>
  <div class="col-9">
    <%= link_to @post.menu.store.name, store_path(@post.menu.store) %>
  </div>

  <div class="col-3">
    <%= I18n.t("post_context") %>
  </div>
  <div class="col-9">
    <%= @post.context %>
  </div>
  <div class="col-3">
    <%= I18n.t("post_may_retry") %>
  </div>
  <div class="col-9">
    <%= I18n.t("post_may_retry_#{@post.may_retry}") %>
  </div>

  <div class="col-3">
    <%= I18n.t("created_at") %>
  </div>
  <div class="col-9">
    <%= @post.created_at %>
  </div>

  <div class="col-3">
    <%= I18n.t("updated_at") %>
  </div>
  <div class="col-9">
    <%= @post.updated_at %>
  </div>

  <div class="col-12 mt-5">
    <%= link_to I18n.t("edit_post"), edit_post_path(@post), class: "btn btn-primary" %>
    <div class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#destroy-post-modal"><%= I18n.t("destroy_post") %></div>
  </div>
</div>


<div class="modal fade" id="destroy-post-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"><%= I18n.t("destroy_post") %></h4>
      </div>
      <%= form_tag post_path(@post), method: :delete, data: { confirm: I18n.t("are_you_sure") } do %>
        <div class="modal-body">
          <%= label_tag I18n.t("user_name") %>
          <%= text_field_tag "post[user_attributes][name]", nil, class: "form-control" %>

          <%= check_box_tag :check_destroy, true, nil, {required: true} %>
          <%= label_tag I18n.t("check_destroy") %>
        </div>
        <div class="modal-footer">
          <%= submit_tag I18n.t("destroy_post"), class: "btn btn-danger" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/stores/index.html.erb
<%= search_form_for @q do |f| %>
  <div class="card p-4">
    <div class="row">
      <div class="col-12 col-md-6 col-lg-3 form-set">
        <%= f.label :name_cont, I18n.t("name") %>
        <%= f.text_field :name_cont, class: "form-control" %>
      </div>
    </div>

    <div class="row justify-content-end">
      <div class="col-auto">
        <%= f.submit t("search"), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

<div class="card p-4 mt-5">
  <h3><%= I18n.t("search_results") %> (<%= @q.result.count %>)</h3>

  <div class="table-responsive">
    <table class="table">
      <thead>
      <tr>
        <th><%= I18n.t("name") %></th>
        <th><%= I18n.t("created_at") %></th>
        <th><%= I18n.t("updated_at") %></th>
      </tr>
      </thead>
      <tbody>
      <% @stores.each do |store| %>
        <tr>
          <td><%= link_to store.name, store_path(store) %></td>
          <td><%= store.created_at.to_s %></td>
          <td><%= store.updated_at.to_s %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <%= will_paginate @stores %>
  </div>
</div>

app/views/stores/show.html.erb
<div class="row">
  <div class="col-3">
    <%= I18n.t("store_name") %>
  </div>
  <div class="col-9">
    <%= @store.name %>
  </div>

  <div class="col-3">
    <%= I18n.t("created_at") %>
  </div>
  <div class="col-9">
    <%= @store.created_at %>
  </div>

  <div class="col-3">
    <%= I18n.t("updated_at") %>
  </div>
  <div class="col-9">
    <%= @store.updated_at %>
  </div>
</div>

<%= render "/posts/share_index", posts: @posts %>
<%= render "/users/share_index", users: @users %>
<%= render "/menus/share_index", menus: @menus %>

app/views/users/_share_index.html.erb
<div class="card p-4 mt-5">
  <div class="table-responsive">
    <table class="table">
      <thead>
      <tr>
        <th><%= I18n.t("user_name") %></th>
        <th><%= I18n.t("created_at") %></th>
        <th><%= I18n.t("updated_at") %></th>
      </tr>
      </thead>
      <tbody>
      <% users.each do |user| %>
        <tr>
          <td><%= link_to user.name, user_path(user) %></td>
          <td><%= user.created_at.to_s %></td>
          <td><%= user.updated_at.to_s %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/index.html.erb
<%= search_form_for @q do |f| %>
  <div class="card p-4">
    <div class="row">
      <div class="col-12 col-md-6 col-lg-3 form-set">
        <%= f.label :name_cont, I18n.t("name") %>
        <%= f.text_field :name_cont, class: "form-control" %>
      </div>
    </div>

    <div class="row justify-content-end">
      <div class="col-auto">
        <%= f.submit t("search"), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

<div class="card p-4 mt-5">
  <h3><%= I18n.t("search_results") %> (<%= @q.result.count %>)</h3>

  <div class="table-responsive">
    <table class="table">
      <thead>
      <tr>
        <th><%= I18n.t("name") %></th>
        <th><%= I18n.t("created_at") %></th>
        <th><%= I18n.t("updated_at") %></th>
      </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.name, user_path(user) %></td>
          <td><%= user.created_at.to_s %></td>
          <td><%= user.updated_at.to_s %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <%= will_paginate @users %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-3">
    <%= I18n.t("name") %>
  </div>
  <div class="col-9">
    <%= @user.name %>
  </div>

  <div class="col-3">
    <%= I18n.t("created_at") %>
  </div>
  <div class="col-9">
    <%= @user.created_at %>
  </div>

  <div class="col-3">
    <%= I18n.t("updated_at") %>
  </div>
  <div class="col-9">
    <%= @user.updated_at %>
  </div>
</div>

<%= render "/posts/share_index", posts: @posts %>

app/views/welcome/index.html.erb
<h2>
  <%= @context %>
</h2>